name: Deploy na EC2 AWS

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build Docker Image
        run: docker build -t mayarayumihino/techapp-pucpr .
      - name: Publish Image to DockerHub
        run: docker push mayarayumihino/techapp-pucpr:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Image from DockerHub
        run: docker pull mayarayumihino/techapp-pucpr:latest
      - name: Delete old container
        run: docker rm -f techapp-pucpr
      - name: Run Docker Container
        run: docker run -d -p 80:5173 --name techapp-pucpr mayarayumihino/techapp-pucpr
